# Generated by Django 5.1.2 on 2025-01-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('weight', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, default='/static/images/phone.jpg', upload_to='images')),
            ],
        ),
    ]
